{
  "type" : "record",
  "name" : "StockAdjusted",
  "namespace" : "com.arcadiaeditions.catalog.inventory.events.avro",
  "fields" : [ {
    "name" : "sku",
    "type" : [ "null", "string" ]
  }, {
    "name" : "quantityDelta",
    "type" : [ "null", "int" ]
  }, {
    "name" : "availableQuantity",
    "type" : [ "null", "int" ]
  }, {
    "name" : "reservedQuantity",
    "type" : [ "null", "int" ]
  }, {
    "name" : "soldQuantity",
    "type" : [ "null", "int" ]
  }, {
    "name" : "reason",
    "type" : "StockAdjustmentReason"
  }, {
    "name" : "reference",
    "type" : [ "null", "string" ]
  }, {
    "name" : "adjustedAt",
    "type" : [ "null", "string" ]
  } ]
}